Implement the BAC pages for managing products and for managing users (including some POS pages already as well)
GEWIS/sudosos-frontend-vue3 pull request #10
Opened 2023-09-23 13:52 UTC by CodeNamedRobin

2023-09-26 19:21 UTC, Yoronex requested changes

2023-09-26 19:21 UTC, Yoronex commented on src/components/AddContainerDialogComponent.vue
> +        <Button severity="danger" @click="saveContainer">{{ $t("c_containerEditModal.save") }}</Button>
These translations are repetitive, because you will have them for every modal ever. So please make a separate group to reduce duplication.

2023-09-26 19:21 UTC, Yoronex commented on src/components/AddContainerDialogComponent.vue
> +    // TODO: Correct error-handling
Todo

2023-09-26 19:21 UTC, Yoronex commented on src/components/BalanceComponent.vue
> +  <CardComponent header="balance" :action="showOption ? 'Increase Online' : ''" routerLink="balance">
Missing translations

2023-09-26 19:21 UTC, Yoronex commented on src/components/BalanceComponent.vue
> +    balanceFromApi.value = `€${(response.data.amount.amount / 100).toFixed(2)}`;
If you make it a Dinero object (which is really easy), you can simply call a method to format it to a beautiful string including currency!

2023-09-26 19:21 UTC, Yoronex commented on src/components/BalanceComponent.vue
> +    return `€${balanceInEuros}`;
Same here

2023-09-26 19:21 UTC, Yoronex commented on src/components/ContainerCardComponent.vue
> +      <TabPanel header="containers" :disabled="true" />
Translation missing

2023-09-26 19:21 UTC, Yoronex commented on src/components/CopyrightBanner.vue
> +  <span class="separator">{{$t("login.separator")}}</span>
This is unnecessary

2023-09-26 19:21 UTC, Yoronex commented on src/components/CopyrightBanner.vue
> +  <a id="tos" href="https://wieditleesttrekteenbak.nl/">{{$t('termsOfService.termsOfService')}}</a>
http://wieditleesttrekteenbak.com *

2023-09-26 19:21 UTC, Yoronex commented on src/components/POSOverviewTableComponent.vue
> +  <CardComponent header="Points of Sale">
Translation missing

2023-09-26 19:21 UTC, Yoronex commented on src/components/ProductComponent.vue
> +}
Empty CSS class, can be deleted

2023-09-26 19:21 UTC, Yoronex commented on src/components/ProductCreateComponent.vue
> +  <Dialog v-model:visible="visible" header="Add Product">
Translation missing

2023-09-26 19:21 UTC, Yoronex commented on src/components/TopupModalComponent.vue
> +    <p>{{$t('c_currentSaldo.topup') + amount }}</p>
Please make the amount a parameter (and insert a full currency string) so it is easier to translate to different languages

2023-09-26 19:21 UTC, Yoronex commented on src/components/TransactionsTableComponent.vue
> +    <Column field="what" header="What" />
Translations missing.

2023-09-26 19:21 UTC, Yoronex commented on src/main.ts
> +app.component('InputText', InputText);-
Minus-symbol?

2023-09-26 19:21 UTC, Yoronex commented on src/utils/formatterUtils.ts
> +    return (value < 10 ? '0' : '') + value;
Please use `.padString()`

2023-09-26 19:21 UTC, Yoronex commented on src/utils/formatterUtils.ts
> +    return (cents / 100).toLocaleString('en', { style: 'currency', currency: 'EUR' });
Dinero

2023-09-26 19:21 UTC, Yoronex commented on src/views/BalanceView.vue
>        <CardComponent action="start payment" header="increase saldo" class="increase-saldo-card" :func="showDialog">
Translation missing

2023-09-26 19:21 UTC, Yoronex commented on src/views/BalanceView.vue
>              <InputNumber v-model="amountValue" placeholder="Price" inputId="amount"/>
Translation missing

2023-09-26 19:21 UTC, Yoronex commented on src/views/HomeView.vue
>        <TransactionsTableComponent class="transactions-table" header="Recent Transactions" action="All Transactions"/>
Translation missing

2023-09-26 19:21 UTC, Yoronex commented on src/views/PointOfSale/POSEditView.vue
> +<!--          TODO: Clean-up whatever the fuck is that above-->
Do it

2023-09-26 19:21 UTC, Yoronex commented on src/views/PointOfSale/POSEditView.vue
> +      // TODO: Error Toasts
Do it

2023-09-26 19:21 UTC, Yoronex commented on src/views/ProductsContainersView.vue
> +          <Column field="image" header="Image" style="width: fit-content">
Translation missing

2023-09-26 19:21 UTC, Yoronex commented on src/views/ProductsContainersView.vue
> +          <Column field="category" header="Category" style="width: 20%">
Translation missing

2023-09-26 19:21 UTC, Yoronex commented on src/views/ProductsContainersView.vue
> +                optionLabel="name"
Translations missing

2023-09-26 19:21 UTC, Yoronex commented on src/views/ProductsContainersView.vue
> +          <Column field="priceInclVat" header="Price">
Translation missing

2023-09-26 19:21 UTC, Yoronex commented on src/views/ProductsContainersView.vue
> +          <Column field="alcoholPercentage" header="Alcohol %">
Translation missing

2023-09-26 19:21 UTC, Yoronex commented on src/views/ProductsContainersView.vue
> +          <Column field="vat" header="VAT">
Translation missing

2023-09-26 19:21 UTC, Yoronex commented on src/views/ProductsContainersView.vue
> +                placeholder="Please select a VAT group"
Translation missing

2023-09-26 19:21 UTC, Yoronex commented on src/views/SingleUserView.vue
> +        <CardComponent header="Personal Info" class="personal-info-card">
Translation missing

2023-09-26 19:21 UTC, Yoronex commented on src/views/SingleUserView.vue
> +<!--            TODO: Fix this actually working-->
Do it!

2023-09-26 19:21 UTC, Yoronex commented on src/views/SingleUserView.vue
> +        <TransactionsTableComponent header="User Transactions" action="none" style="width: 100%;"/>
Translation missing

2023-09-27 06:52 UTC, JustSamuel requested changes
I didn´t check everything but since @roy is also checking this ill just request changes.

2023-09-27 06:52 UTC, JustSamuel commented on src/components/AddContainerDialogComponent.vue
> +    // TODO: Correct error-handling
Please fix before merge.

2023-09-27 06:52 UTC, JustSamuel commented on package.json
> +    "vue-i18n": "^9.2.2",
?

2023-09-27 06:52 UTC, JustSamuel commented on package.json
>      "vue-i18n": "^9.2.2"
?

2023-09-27 06:52 UTC, JustSamuel commented on src/views/UserOverView.vue
> +// TODO: Fix sorting
Either make an issue or fix it.

2023-09-27 06:52 UTC, JustSamuel commented on src/views/UserOverView.vue
> +//TODO: Fix user type filtering
Either make an issue or fix it.

2023-09-27 06:52 UTC, JustSamuel commented on src/views/UserOverView.vue
> +      <!--      TODO: Change this to gewisId, is id for testing purposes-->
Do it or make an issue of it

2023-09-27 06:52 UTC, JustSamuel commented on src/views/UserOverView.vue
> +    <DataTable
onClick on a row does nothing; but still looks like you "clicked" something. I.e, it gives a blue border. Either remove it or make it do something on click.

2023-09-27 06:52 UTC, JustSamuel commented on src/views/UserOverView.vue
> +onMounted(async () => {
Order function based on call hierachy, onMounted is first so should be near the top.

2023-09-27 06:52 UTC, JustSamuel commented on src/views/UserOverView.vue
> +  const response = await apiService.user.createUser(createUserRequest);
prefer .then and .catch

2023-09-27 06:52 UTC, JustSamuel commented on src/views/UserOverView.vue
> +.usertable-header {
prefer in-line bootstrap classes instead.

2023-09-27 06:52 UTC, JustSamuel commented on src/views/UserOverView.vue
> +  display: flex;
prefe rin-line bootstrap classes instead.

2023-09-27 06:52 UTC, JustSamuel commented on src/views/UserOverView.vue
> +  display: flex;
prefer inline bootstrap classes instead.

2023-09-27 06:52 UTC, JustSamuel commented on src/views/UserOverView.vue
> +  justify-content: flex-end;
prefer inline bootstrap classes instead.

2023-09-27 06:52 UTC, JustSamuel commented on src/views/UserOverView.vue
> +          <label for="first-name">{{ $t('c_userTable.firstName') }}</label>
fix translations, or make an issue.

2023-09-27 06:52 UTC, JustSamuel commented on src/views/UserOverView.vue
> +          <span class="error-text">{{ errors.firstName }}</span>
Validation errors are usually location below the input, or at least presented in a nicer way. Give ti some padding, make it red or in general look at how inut validation errors are presented.

2023-09-27 06:52 UTC, JustSamuel commented on src/views/UserOverView.vue
> +          <Button severity="danger" type="submit">{{ $t('c_confirmationModal.Save' )}}</Button>
Doesn' t do anything.

2023-09-27 06:52 UTC, JustSamuel commented on src/views/UserOverView.vue
> +          <Button severity="danger" outlined @click="visible = false">{{ $t('c_confirmationModal.Cancel' )}}</Button>
Should clear input fields on close.

2023-09-27 06:52 UTC, JustSamuel commented on src/views/UserOverView.vue
> +    Number.MAX_SAFE_INTEGER,
You sure about this?

2023-09-27 06:52 UTC, JustSamuel commented on src/views/UserOverView.vue
> +const visible: Ref<boolean> = ref(false);
blocks of ref definitions preferbly have a white line before and after them, makes it clearer imho.

2023-09-27 06:52 UTC, JustSamuel commented on src/views/SingleUserView.vue
> +<!--TODO: Extract input validation styling-->
Either make an issue or do this.

2023-09-27 06:52 UTC, JustSamuel commented on src/views/SingleUserView.vue
> +<!--      TODO: Refactor to extract this component-->
Either make an issue or do this.

2023-09-27 09:39 UTC, CodeNamedRobin commented on src/components/AddContainerDialogComponent.vue
> +        <Button severity="danger" @click="saveContainer">{{ $t("c_containerEditModal.save") }}</Button>
For now I will use these, but I opened issue #17 to rework all translations in the future.

2023-09-27 09:41 UTC, CodeNamedRobin commented on src/components/AddContainerDialogComponent.vue
> +    // TODO: Correct error-handling
This is now issue #18.

2023-09-27 09:42 UTC, CodeNamedRobin commented on src/components/BalanceComponent.vue
> +  <CardComponent header="balance" :action="showOption ? 'Increase Online' : ''" routerLink="balance">
Fixed.

2023-09-27 14:10 UTC, CodeNamedRobin commented on src/views/PointOfSale/POSEditView.vue
> +      // TODO: Error Toasts
Issue #18

2023-09-27 14:19 UTC, CodeNamedRobin commented on src/components/AddContainerDialogComponent.vue
> +    // TODO: Correct error-handling
Issue #18 for hackathon

2023-09-27 14:21 UTC, CodeNamedRobin commented on src/views/UserOverView.vue
> +// TODO: Fix sorting
Issue #19

2023-09-27 14:21 UTC, CodeNamedRobin commented on src/views/UserOverView.vue
> +//TODO: Fix user type filtering
Issue #19

2023-09-27 14:24 UTC, CodeNamedRobin commented on src/views/UserOverView.vue
> +      <!--      TODO: Change this to gewisId, is id for testing purposes-->
It be develop so will fix in prod

2023-09-27 15:12 UTC, CodeNamedRobin commented on src/views/UserOverView.vue
> +  const response = await apiService.user.createUser(createUserRequest);
Will fix later in separate branch. Issue #20

2023-09-27 16:08 UTC, CodeNamedRobin commented on src/views/UserOverView.vue
> +    Number.MAX_SAFE_INTEGER,
Yes.

2023-09-27 16:09 UTC, CodeNamedRobin commented on src/views/UserOverView.vue
> +const visible: Ref<boolean> = ref(false);
Fair enough.

2023-09-27 16:09 UTC, CodeNamedRobin commented on src/views/SingleUserView.vue
> +<!--TODO: Extract input validation styling-->
Duplicate of #14

2023-09-27 16:13 UTC, CodeNamedRobin commented on src/views/SingleUserView.vue
> +<!--      TODO: Refactor to extract this component-->
Issue #21

2023-09-27 16:14 UTC, CodeNamedRobin commented on src/components/BalanceComponent.vue
> +    balanceFromApi.value = `€${(response.data.amount.amount / 100).toFixed(2)}`;
I'll make this a hacktoberfest issue since it's quite easy to fix. (and I'm also pretty lazy)

2023-09-27 16:24 UTC, merged